### ISSUE TITLE
Uncaught Error: infinite rendering invalidation detected, with ember-pikaday 2.2.1

### ISSUE THREAD

**Issue by iirving** [edgycircle/ember-pikaday#136]
with     "ember-pikaday": "2.2.1" and 
Ember             : 2.11.2
Ember Data        : 2.11.3
jQuery            : 3.1.1

getting the "infinite rendering invalidation detected" error (and the web paper going blank) when 'opening' the component and selecting the minDate (which is the current date).

work around : reverting back to the ember-pikaday": "2.2.0" corrected the bad behavior

  {{pikaday-input
      format="dddd MMMM DD, YYYY"
      value=selectedDate
      readonly="readonly"
      minDate=minDate
      required=true
      onSelection=(action (mut selectedDate))
      size="30"
      class="broadcast-date"
  }}

I've included the console dump if that that helps! (thank you for your work!)

Uncaught Error: infinite rendering invalidation detected
    at Array.p (vendor-88e896e4627d876923d57aa78a3e237e.js:10)
    at d._trigger (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d.end (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d.run (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d._trigger (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d.end (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d.run (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d._trigger (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d.end (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
    at d.run (vendor-88e896e4627d876923d57aa78a3e237e.js:8)
p @ vendor-88e896e4627d876923d57aa78a3e237e.js:10
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
_trigger @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
end @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
run @ vendor-88e896e4627d876923d57aa78a3e237e.js:8
setDate @ vendor-88e896e4627d876923d57aa78a3e237e.js:52
C.s._onMouseDown @ vendor-88e896e4627d876923d57aa78a3e237e.js:52

**Comment by duizendnegen** [comment]
Could you verify whether this is also the case with 2.2.0? I have some suspicions about what's going on but just want to verify.

**Comment by iirving** [comment]
no problems with ember-pikaday 2.2.0

**Comment by jedrula** [comment]
I think this is what happens:
problem is:
1. component is rendered with minDate set to new Date() which is the current time with hours, minutes …
```
{{!-- today: new Date() is what I have in the controller --}}
{{pikaday-input
  minDate=today
  value=someDate
  onSelection=(action (mut someDate))
}}
```
2. user clicks on input and chooses the edge minDate from the calendar
3. mut helper updates date to the beginning of the chosen day (this is what is returned from the pikaday)
4. didUpdateAttrs fire - the muted value is also passed in as a value
5. setMinDate is triggered
6. in the sync queue the `value && value < minDate` is true since value was set to the benign of the chosen (minDate) day while the actual value of minDate is bigger - it is the same day but with some hours and minutes
7. pikaday.setDate is triggered
8.  onSelection callback (which is set to our mut helper) is triggered with an argument which has the hours and minutes wiped out again by the piked (back to step 1)
9. …didUpdateAttrs fire - we are back at point 2 and go on in the infinite loop

I have an idea on how to fix it and will try to submit a PR - the comparison in the sync queue should only care about year, month and day

**Comment by jedrula** [comment]
I think the comparison needs to be changed to:
`if (value && moment(value).isBefore(minDate, 'day')) {`
