### ISSUE TITLE
yearRange doesn't work

### ISSUE THREAD

**Issue by jeffreybiles** [edgycircle/ember-pikaday#36]
I put in 2004,2008 as yearRange, and it allowed me to select dates both before 2004 and after 2008.

Video here: https://bilesjeffrey.wistia.com/medias/gh5c6s4ujb

I also tried with single-integer ranges, with similar not-working-ness.

**Comment by stravid** [comment]
Thank you for the report and nice video. I checked with Pikaday what the expected behaviour is and found out following:

The year range is only used for the year select element. If you want to enforce a minimum and maximum date you should use `minDate` and `maxDate` in Pikaday. This is currently not yet supported but I would love to see it implemented with tests :)
