### ISSUE TITLE
How to show today button?

### ISSUE THREAD

**Issue by dewitt-li** [edgycircle/ember-pikaday#51]
Does the addon has the feature of showing a Today button, which will highlight today's date when click?

**Comment by stravid** [comment]
Hello @dewitt-li this addon currently has no such feature.

Pikaday itself has an method to do this `picker.gotoToday()`, this could be used if you decide to extend the component and implement your own logic.

Otherwise you could always select the current date by setting the value to `new Date()` which is always today.
