### ISSUE TITLE
Time-enabled Pikaday

### ISSUE THREAD

**Issue by utilityboy** [edgycircle/ember-pikaday#97]
Hi,

There is a very well maintained fork of pikaday that adds time-picking support as well (https://github.com/owenmead/Pikaday/).  dbushnell even endorses this fork to an extent for people looking for date/time picking.

I'm planning on forking this repo to add support, but wanted to check to see if you thought there was another way to go about it  I'm fairly certain you wouldn't want to change your dependency to the pikaday fork, but thought I'd doublecheck first.

Thanks for the great work!

**Comment by stravid** [comment]
Thanks for the kind words and asking about my opinion. You are right when it comes to the dependency, at the moment I don't see a reason to swap it. Mainly because personally I would try to keep a data input separate from a time input in an application.

But that's only my opinion and there are good reasons to do otherwise. I wish you good luck with implementing the feature and hope `ember-pikaday` makes it easy for you :)

**Comment by utilityboy** [comment]
@stravid sounds good.  I'll fork this and let you know when it's ready.   If you have time for review and think it's decent, perhaps we can cross-link to each other in the readme.

**Comment by stravid** [comment]
Sure thing! Just keep me in the loop and we go from there :)

**Comment by stravid** [comment]
@andycochran no, I can't recommend one.

**Comment by utilityboy** [comment]
@andycochran no, sadly.  We decided to use the power-select calendar and time pickers in the end.  Even though this is no longer maintained, it does work well for us: https://github.com/RyanNerd/ember-power-timepicker
